// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svpoyasxewptlcuupxpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cG95YXN4ZXdwdGxjdXVweHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTUxMTgsImV4cCI6MjA2NjM3MTExOH0.RBhEpi6CI1n7slppKRVZxsApf8SOQkBXS5-Bx18Ms8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);